from tests.generic_exception import LogException